### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by cyrill100** [maartenpaauw/MMM-HLTV#1]
Hi there 
Is this a Module for MagicMirror and does it actually work?

**Comment by maartenpaauw** [comment]
Hello! This is indeed a module for the MagicMirror. It's still work in progress. Will go further if I've time.

**Comment by cyrill100** [comment]
Alright thanks for the Answer, guess i will wait until the full release.

**Comment by maartenpaauw** [comment]
@cyrill100 Thanks for the interest! For now it will be a module which will show the ongoing and upcoming matches. If you have more ideas for this module feel free to create an issue!

**Comment by cyrill100** [comment]
@maartenpaauw Actually thats exactly what im searching, but maybe you could add like the last 5 matches or something and that you could choose as a option which Teams you wanna see.

**Comment by maartenpaauw** [comment]
@cyrill100 Picking specific teams could be a feature for the future. I'll first finish the base code. But thanks for the suggestions. Could you maybe create a separate issue for this?

**Comment by cyrill100** [comment]
@maartenpaauw  Gona close that one thanks for the Informations.
