### ISSUE TITLE
Pick teams to list

### ISSUE THREAD

**Issue by cyrill100** [maartenpaauw/MMM-HLTV#2]
Like i told you in the other "issue" the option to pick which teams you want to see would be great.

**Comment by maartenpaauw** [comment]
Hi @cyrill100. I finally had the time to work on this project again :). Today I picked up this issue. There is a branch `feature/filter-teams`. Feel free to test it out.

**Comment by cyrill100** [comment]
Hi @maartenpaauw 
Thanks for your reply i was just looking at your plugin like 1 week ago and i thought you stoped completly great to have some Intresting addons for my Mirror.

**Comment by maartenpaauw** [comment]
This feature is merge right now into develop. Feel free to try it out.
